### PR TITLE
Java Port

### PR DESCRIPTION
**Pull request by apemanzilla**
Finally ditching bloated JVM languages

- [x] net.clgd.ccemux
- [x] net.clgd.ccemux.emulation
- [x] net.clgd.ccemux.emulation.tror
- [x] net.clgd.ccemux.emulation.tror.tests
- [x] net.clgd.ccemux.rendering
- [x] net.clgd.ccemux.rendering.awt
- [x] net.clgd.ccemux.rendering.tror

### CODE REVIEW

**Comment by apemanzilla** [comment]
@Lignumm @SquidDev anything to change before merging?

**Comment by SquidDev** [comment]
As long as CCTweaks works I'm all 👌. I presume you've tested changing `cctweaks.*` config options?

**Comment by Lemmmy** [comment]
fist me

**Comment by apemanzilla** [comment]
@SquidDev yep, seems to be working properly.

**Comment by Lemmmy** [comment]
merge
erge
rge
ge
e

**Comment by SquidDev** [comment]
:shift:

**Pull request merged**
