### PR TITLE
CCTweaks integration

### LINKED ISSUE #14: CCTweaks support in rewrite
@SquidDev in case you haven't yet seen it, we're working on a rewrite of CCEmuX (old version was pretty poor coding style, lots of `throws Exception` and whatnot, see the `rewrite` and `rw-emulation` branches) so we need to do the CCTweaks stuff again.

### PR DESCRIPTION
**Pull request by SquidDev**
Currently looking for feedback and thoughts.

#### Issues
 - [x] Breaks the version number: either don't use `Class.getPackage` or fix CCTweak's class loader
 - [x] Option to disable/enable CCTweaks: don't know what you want by default
 - ~~Dynamically download CCTweaks rather than package it?~~
 - [x] Set CCTweaks' config from CCEmuX's config - not sure how to do this as CCTweaks uses a global config.

Closes #14

### CODE REVIEW

**Comment by apemanzilla** [comment]
If you're OK with it I'd prefer to package CCTweaks with CCEmuX. Less stuff to download means fewer potential points of failure.

**Comment by SquidDev** [comment]
Sure, I don't mind either way - just wanted to know your thoughts. Do you want CCTweaks enabled by default, or at least an option to disable it?

**Comment by apemanzilla** [comment]
I'm fine with either as long as it can be en/disabled via config and/or CLI.

**Comment by Lignumm** [comment]
I think it should be enabled by default. CCTweaks is basically the OptiFine of ComputerCraft, you'd only really want to disable it if it's causing trouble.

**Comment by SquidDev** [comment]
> CCTweaks is basically the OptiFine of ComputerCraft

This is what worries me: sometimes CCTweaks breaks programs and I don't want you guys getting blamed. *However* CCTweaks is pretty useful and ideally people would write programs to work with it.

**Comment by Lignumm** [comment]
Don't worry about that, it's sort of a good way to find bugs in CCTweaks :stuck_out_tongue:. Aside from that, LuaJC is disabled by default, which is the primary cause of problems, no?

**Comment by SquidDev** [comment]
Well the biggest compatibility issue is [this](https://github.com/BTCTaras/kristwallet/pull/11) and I don't really want to change it til I can find a better solution.  However most of the time this isn't an issue.

I'd have said that luajc is pretty stable, but I found a bug a couple of weeks ago :frowning:.

Anyways,  if you guys are fine with leaving it enabled I'm not going to grumple. I'll try to add a config option on Sunday: I'll be away for the weekend so can't get round to it beforehand.

**Comment by SquidDev** [comment]
I've added a `cctweaks.enabled` config option. This uses the same naming convention as other CCTweaks config options, though I'm happy to switch to `cctweaksEnabled` if you'd prefer.

**Comment by Lignumm** [comment]
```
[main] WARN CCEmuX - Cannot find custom rewrite /org/squiddev/cctweaks/lua/patch/binfs/FileSystem_PatchException.class
```
Is this anything to worry about @SquidDev?

Other than that, looks good to me. Any objections @apemanzilla @Lemmmy?

**Comment by SquidDev** [comment]
> Is this anything to worry about @SquidDev?

Nope, this is expected behaviour.

**Comment by apemanzilla** [comment]
Looks good here.

**Comment by Lemmmy** [comment]
✅

**Comment by Lignumm** [comment]
Righto, let's merge! :tada:

**Comment by Lemmmy** [comment]
💩

**Pull request merged**
