### PR TITLE
[WIP] LWJGL3 Renderer

### PR DESCRIPTION
**Pull request by Lignumm**

### CODE REVIEW

**Comment by apemanzilla** [comment]
Any reason that we're using LWJGL 3.0.0b and not 3.1.1?

**Comment by CrazedProgrammer** [comment]
YES

**Comment by Lignumm** [comment]
@apemanzilla No

**Comment by Lignumm** [comment]
@apemanzilla I saw you deprecated our current renderer enum, I haven't looked into it much, but will that conflict with this branch?

**Comment by Lignumm** [comment]
It is finished. Please review.

**Comment by Lignumm** [comment]
Multiple windows don't work, and I also forgot the ctrl shortcuts.

**Comment by apemanzilla** [comment]
@Lignumm no, it won't. The `Renderer` class is unchanged and instead of using the enum we'll just create a simple built-in plugin that registers the rendering method.

**Comment by Lignumm** [comment]
ok

**Comment by apemanzilla** [comment]
Should we close this due to unresolvable issues (i.e. multi-window support)?

**Comment by Lignumm** [comment]
At least for now, yes.

**Comment by Lemmmy** [comment]
i dont think you'll get a working opengl backend unless you drop multi-window support. do it like ccemuredux does, with one master window.

**Comment by Lignumm** [comment]
@Lemmmy Yes, we've discussed that on Slack. We're planning on maybe using LibGDX again for that.

**Pull request closed without merging**
