### PR TITLE
Corrected a huge problem

### PR DESCRIPTION
**Pull request by BTCTaras**
Wouldn't wanna trigger brits

### CODE REVIEW

**Comment by Lemmmy** [comment]
ape no

**Comment by BTCTaras** [comment]
this is an outrage

**Comment by inklit** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by Codicassert** [comment]
is this next-level racism

**Comment by CrazedProgrammer** [comment]
very good yes

**Comment by apemanzilla** [comment]
as an american im triggered by your incorrect spelling of the word "license"

**Comment by Codicassert** [comment]
make it "licencse" then

**Comment by Lignumm** [comment]
thank you taras for being so considerate

**Pull request merged**
