### PR TITLE
Made the license cool beyond belief

### PR DESCRIPTION
**Pull request by Lignumm**
This licence is way too :cool: to be modified.

### CODE REVIEW

**Comment by BTCTaras** [comment]
i approve this change

**Comment by inklit** [comment]
this is good change

**Comment by Lignumm** [comment]
Looks good to me :white_check_mark: :white_check_mark: :white_check_mark:. You best believe we mergin' this :sunglasses: :sunglasses: !!

**Comment by Lignumm** [comment]
vive la révolution!!!

**Comment by BTCTaras** [comment]
we have corrected the non-issue #29 and brought balance to #27

**Pull request merged**
