### PR TITLE
Add terminal margin

### PR DESCRIPTION
**Pull request by Lignumm**

### CODE REVIEW

**Comment by SquidDev** [comment]
Some thoughts/comments:

 - `mapPointToCC` doesn't handle the margin currently
 - Maybe just draw a black boarder like [this comment](https://github.com/dan200/ComputerCraft/issues/51#issuecomment-164748461) instead of using the background colour. Though this is inconsistent with normal CC.

**Comment by Lemmmy** [comment]
don't draw a black border please make it look like normal cc

**Comment by Lignumm** [comment]
We could also render the subpixels in realtime instead of from a texture. This way, we can expand the subpixel over the border if needed.

That shouldn't be all too difficult to do, and it'd also allow for some other cool stuff, perhaps something like `ccemux.setSubpixelColours`, allowing you to set the colour of each individual subpixel.

But of course, there should be a setting for whatever correction we make. Some people will want the emulator to be true to real CC for various reasons.

**Comment by Lignumm** [comment]
@SquidDev There's that done as well.

**Pull request merged**
